[package]
name = "mkripper"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amqprs = "1.6.2"
serde_json = "1.0.120"
sysinfo = "0.30.13"
tokio = { version = "1.38.1", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
