[package]
name = "mkripper"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amqprs = "1.6.0"
serde_json = "1.0.116"
sysinfo = "0.30.11"
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
