[package]
name = "mkripper"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amqprs = "1.5.3"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
