[package]
name = "pi_terminal"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amqprs = "2.0.0"
bytesize = { version = "1.3.0", features = ["serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.13"
fltk = { version = "1.4.33", features = ["fltk-bundled"] }
fltk-table = "0.3.2"
fltk-theme = "0.7.3"
lazy_static = "1.5.0"
rppal = "0.19.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sqlite = "0.36.1"
syact = "0.13.7"
sys-info = "0.9.1"
tokio = { version = "1.40.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["serde", "v7"] }

[dev-dependencies]
tokio-test = "*"
