[package]
name = "pi_terminal"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
bytesize = { version = "1.3.0", features = ["serde"] }
crossbeam = "0.8.2"
crossbeam-channel = "0.5.8"
fltk = { version = "1.4.4", features = ["fltk-bundled"] }
fltk-table = "0.3.1"
fltk-theme = "0.7.0"
lazy_static = "1.4.0"
rppal = "0.15.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
syact = { version = "0.12.0", features = [ "rasp" ] } 
sys-info = "0.9.1"

[dev-dependencies]
tokio-test = "*"
