[package]
name = "pi_terminal"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]
amqprs = "1.6.2"
bytesize = { version = "1.3.0", features = ["serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.13"
fltk = { version = "1.4.32", features = ["fltk-bundled"] }
fltk-table = "0.3.1"
fltk-theme = "0.7.2"
lazy_static = "1.5.0"
rppal = "0.18.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sqlite = "0.36.0"
syact = { version = "0.13.7", features = ["rasp"] }
sys-info = "0.9.1"
tokio = { version = "1.38.1", features = ["full"] }

[dev-dependencies]
tokio-test = "*"
