---
# Volumes are HOST directory and then CONTAINER directory

services:
  ripper1:
    image: mediakraken/mkripper:dev
    environment:
      - WAIT_HOSTS=rabbitmq:5672
      - WAIT_TIMEOUT=180
    command: sh -c "/wait && /ripper"
    devices:
      - '/dev/sr0:/dev/sr0'
    privileged: true 
    stop_grace_period: 30s
    stop_signal: SIGUSR1

  ripper2:
    image: mediakraken/mkripper:dev
    environment:
      - WAIT_HOSTS=rabbitmq:5672
      - WAIT_TIMEOUT=180
    command: sh -c "/wait && /ripper"
    devices:
      - '/dev/sr1:/dev/sr0'
    privileged: true 
    stop_grace_period: 30s
    stop_signal: SIGUSR1

  rabbitmq:
    image: mediakraken/mkrabbitmq:dev
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_IO_THREAD_POOL_SIZE=256
    stop_grace_period: 30s
    stop_signal: SIGTERM
    ports:
      - "5672:5672"
      # https management port
      - "15671:15671"
      # http management port
      - "15672:15672"

  scanservjs:
    image: sbs20/scanservjs:latest
    privileged: true
    stop_grace_period: 30s
    stop_signal: SIGTERM
    ports:
      - "8080:8080"
    volumes:
      - /var/run/dbus:/var/run/dbus

