[package]
name = "ripper_client"
version = "0.0.1"
edition = "2021"

[profile.release]
panic = 'abort'
strip = "symbols"
lto = true
codegen-units = 1

[dependencies]


[dev-dependencies]
tokio-test = "*"
